    <nav class="navbar">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="topic.php">Topic</a></li>
            <li><a href="quiz.php">Quiz</a></li> 
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="enhancements2.php">Enhancements JS</a></li>
            <li><a href="supervisor.php">Supervisor</a></li>
            <li><a href="phpenhancements.php">Enhancements PHP</a></li>
          </ul>
    </nav>